global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'elevator-system'
    static_configs:
      - targets: ['elevator-system:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s